package org.crossv.expressions;

enum EvalOp {
	DEVIDE, MODULO, MULTIPLY, PLUS, SUBTRACT, LEFT_SHIFT, RIGHT_SHIFT, GREATER_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN, LESS_THAN_OR_EQUAL, EQUAL, NOT_EQUAL, AND, OR, XOR, OR_ELSE, AND_ALSO
}
